---
ec2_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
ec2_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
ec2_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
ec2_region_az1: "{{ lookup('env', 'AWS_DEFAULT_AZ1') }}"
ec2_region_az2: "{{ lookup('env', 'AWS_DEFAULT_AZ2') }}"
ec2_region_az3: "{{ lookup('env', 'AWS_DEFAULT_AZ3') }}"
ec2_region_az4: "{{ lookup('env', 'AWS_DEFAULT_AZ4') }}"
