# deploys core fleet units to coreos cluster
# core units include: skyDNS, registrator

# skyDNS
- name: Copy skydns.service
  copy: src="{{ gaia_fleet_location }}/skydns.service" dest=~/skydns.service
- name: Stop and destroy old skydns.service
  shell: "fleetctl stop skydns.service && fleetctl destroy skydns.service"
  ignore_errors: True
- name: Start skydns.service
  shell: "fleetctl submit skydns.service && fleetctl start skydns.service"

# registrator
- name: Copy registrator.service
  copy: src="{{ gaia_fleet_location }}/registrator.service" dest=~/registrator.service
- name: Stop and destroy old registrator.service
  shell: "fleetctl stop registrator.service && fleetctl destroy registrator.service"
  ignore_errors: True
- name: Start registrator.service
  shell: "fleetctl submit registrator.service && fleetctl start registrator.service"
