# playbook to deploy all services
- include: detect_cluster.yaml

# allow executing ansible on coreos cluster members
- name: Bootstrap coreos cluster members with python
  hosts: coreos_cluster
  gather_facts: False
  roles:
    - role: defunctzombie.coreos-bootstrap

# deploy core + gaia services
- name: Deploy all services
  hosts: coreos_cluster_manager
  gather_facts: False
  vars:
    gaia_fleet_location: "{{ gaia_fleet_dir | default('../gaia-fleet') }}"
  roles:
    - { role: deploy_fleet_services, services: "{{ all_services }}" }
