# deploys core services. Assumes ansible execution on cluster is possible.

# detect coreos cluster
- include: detect_cluster.yaml

- name: Deploy core services
  hosts: coreos_cluster_manager
  gather_facts: False
  vars:
    gaia_fleet_location: "{{ gaia_fleet_dir | default('../gaia-fleet') }}"
  roles:
    # core services. Must match core services in deploy_all.yaml
    - { role: deploy_fleet_service, service_file: 'skydns.service' }
    - { role: deploy_fleet_service, service_file: 'registrator.service' }
    - role: deploy_mq
    - role: deploy_influxdb
