# allow executing ansible on coreos cluster members
- include: coreos_bootstrap_{{ provisioner }}.yaml

# deploy core + gaia services
- name: Deploy all services
  hosts: coreos_cluster_manager
  gather_facts: False
  vars:
    gaia_fleet_location: "{{ gaia_fleet_dir | default('.gaia-fleet') }}"
  roles:
    - { role: download_fleet_units, services: "{{ all_services }}" }
    - { role: deploy_fleet_services, services: "{{ all_services }}" }
