# This playbook deploys services implemented in gaia

# detect coreos cluster
- include: detect_cluster.yaml

- name: Deploy GAIA services
  hosts: coreos_cluster_manager
  gather_facts: False
  vars:
    gaia_fleet_location: "{{ gaia_fleet_dir | default('../gaia-fleet') }}"
  roles:
    # gaia services. Must match gaia services in deploy_all.yaml
    - role: deploy_grafana
    - role: deploy_events_indexer
    - role: deploy_sts
    - role: deploy_mgs
    - role: deploy_haproxy
