# allow executing ansible on coreos cluster members
- include: coreos_bootstrap_{{ provisioner }}.yaml

# destroy gaia services
- name: Destroy gaia services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: destroy_fleet_services, services: "{{ gaia_services }}" }
