# allow executing ansible on coreos cluster members
- include: coreos_bootstrap_{{ provisioner }}.yaml

# destroy core + gaia services
- name: Destroy all services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: destroy_fleet_services, services: "{{ all_services }}" }
