# playbook which selects one machine from coreos cluster for cluster management operations
# and creates groups coreos_cluster_manager (first cluster machine) and coreos_cluster (all cluster machines)
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/all.yaml
    - group_vars/envs/{{ env | default("develop") }}/ssh_config.yaml
  tasks:
    - include: "{{ provisioner }}.yaml"
    # create new group for cluster members. This is more accurate than inventory groups, since they are per each tag or security group.
    # Its also more easy to use for iteration.
    - name: create host group for coreos cluster
      add_host: >
        hostname="{{item}}"
        groupname=coreos_cluster
        ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
      with_items: "{{ coreos_ips }}"
    # for execution of fleetctl commands we need any running coreos instance. We create group of just one IP that is used as cluster manager.
    - name: create host group for coreos cluster manager
      add_host: >
        hostname="{{coreos_manager_ip}}"
        groupname=coreos_cluster_manager
        ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
