# playbook which selects one machine from coreos cluster for cluster management operations
# and creates groups coreos_cluster_manager (first cluster machine) and coreos_cluster (all cluster machines)
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/all.yaml
    - group_vars/envs/{{ env | default("develop") }}/ssh_config.yaml
  tasks:
    # detect coreos cluser information
    - name: Detect CoreOS cluster info
      shell: "aws ec2 describe-instances --filters 'Name=instance-state-name,Values=running' 'Name=tag:Name,Values={{ coreos_instance_tags.Name }}' 'Name=tag:group,Values={{ coreos_instance_tags.group }}' 'Name=tag:env,Values={{ coreos_instance_tags.env }}' 'Name=tag:type,Values={{ coreos_instance_tags.type }}' --output json"
      register: coreos_info_out
    - set_fact:
        coreos_ips: "{{ coreos_info_out.stdout | from_json | ec2_instance_info('PrivateIpAddress') }}"
    - set_fact:
        coreos_manager_ip: "{{ coreos_ips[0] }}"

    # create new group for cluster members. This is more accurate than inventory groups, since they are per each tag or security group.
    # Its also more easy to use for iteration.
    - name: create host group for coreos cluster
      add_host: >
        hostname="{{item}}"
        groupname=coreos_cluster
        ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
      with_items: "{{ coreos_ips }}"
    # for execution of fleetctl commands we need any running coreos instance. We create group of just one IP that is used as cluster manager.
    - name: create host group for coreos cluster manager
      add_host: >
        hostname="{{coreos_manager_ip}}"
        groupname=coreos_cluster_manager
        ansible_python_interpreter="PATH=/home/core/bin:$PATH python"
