# allow executing ansible on coreos cluster members
- include: coreos_bootstrap_{{ provisioner }}.yaml

# start gaia services
- name: Start gaia services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: start_fleet_services, services: "{{ gaia_services }}" }
