# allow executing ansible on coreos cluster members
- include: coreos_bootstrap_{{ provisioner }}.yaml

# start core + gaia services
- name: Start all services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: start_fleet_services, services: "{{ all_services }}" }
