- include: detect_cluster.yaml

# allow executing ansible on coreos cluster members
- name: Bootstrap coreos cluster members with python
  hosts: coreos_cluster
  gather_facts: False
  roles:
    - role: defunctzombie.coreos-bootstrap

# start core + gaia services
- name: Start all services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: start_fleet_services, services: "{{ all_services }}" }
