- include: detect_cluster.yaml

# stop core + gaia services
- name: Stop all services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: stop_fleet_services, services: "{{ all_services }}" }
