- include: detect_cluster.yaml

# stop gaia services
- name: Stop gaia services
  hosts: coreos_cluster_manager
  gather_facts: False
  roles:
    - { role: stop_fleet_services, services: "{{ gaia_services }}" }
