---
ssh_config_file: ssh_config

bastion_instance_tags: { "Name": "bastion", "group": "gaia", "env": "develop", "type": "bastion-vm" }
bastion_user: "ubuntu"
bastion_keypair_file: bastion-key-dev.pem

bastion_nat_instance_tags: { "Name": "Bastion_NAT", "group": "gaia", "env": "develop" }
bastion_nat_keypair_file: bastion-nat-key-dev.pem

docker_registry_instance_tags:  { "Name": "docker-registry", "group": "gaia", "env": "develop", "type": "docker-registry-vm" }
docker_registry_keypair_file: docker-registry-key-dev.pem

coreos_instance_tags:  { "Name": "coreos", "group": "gaia", "env": "develop", "type": "cluster_node" }
coreos_keypair_file: coreos-key-dev.pem

etcd_instance_tags:  { "Name": "etcd", "group": "gaia", "env": "develop", "type": "cluster_node" }
etcd_keypair_file: etcd-key-dev.pem

nat_instance_tags: { "Name": "NAT", "group": "gaia", "env": "develop" }
nat_keypair_file: nat-key-dev.pem
