---
ec2_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
ec2_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
ec2_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"

# CoreOS AWS tags
coreos_instance_tags:  { "Name": "coreos", "group": "gaia", "env": "{{ environ }}", "type": "cluster_node" }

# ssh_config file name
ssh_config_file: "ssh_config_{{ env_nick[environ] }}"

# parametric services must have template file specified
# order of services defines starting order via fleet. Services are stopped in reverse order.
system_services:
  - {name: 'logentries.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'cadvisor.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'skydns.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'registrator.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'vault.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'vault-unseal.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}

platform_services:
  - {name: 'rabbitmq@master.service', template: 'rabbitmq@.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'es.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}

gaia_services:
  - {name: 'kibana.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'es-events-indexer.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'dex-overlord.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'dex-worker.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'dex-client-config.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'security-token-service.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'metrics-gateway-service.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'result-upload-service.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
#  - {name: 'sample-weather-processor.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master}
  - {name: 'circleci-tests-processor.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'jenkins-tests-processor.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'alm-issue-change-processor.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'agm-issue-change-processor.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'haproxy.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}
  - {name: 'webhook-service.service', url: 'https://raw.githubusercontent.com/gaia-adm/gaia-fleet', branch: 'master'}

all_services: "{{ system_services + platform_services + gaia_services }}"
