# deploys rabbit mq

- name: Stop and destroy old rabbitmq@.service
  shell: "fleetctl stop rabbitmq@master.service && fleetctl destroy rabbitmq@master.service && fleetctl destroy rabbitmq@.service"
  ignore_errors: True
- name: Stop and destroy old rabbitmq.data@.service
  shell: "fleetctl stop rabbitmq.data@master.service && fleetctl destroy rabbitmq.data@master.service && fleetctl destroy rabbitmq.data@.service"
  ignore_errors: True

# rabbitmq.data@.service
- name: Copy rabbitmq.data@.service
  copy: src="{{ gaia_fleet_location }}/rabbitmq.data@.service" dest=~/rabbitmq.data@.service
- name: Start rabbitmq.data@.service
  shell: "fleetctl submit rabbitmq.data@.service && fleetctl start rabbitmq.data@master.service"

# rabbitmq@.service
- name: Copy rabbitmq@.service
  copy: src="{{ gaia_fleet_location }}/rabbitmq@.service" dest=~/rabbitmq@.service
- name: Start rabbitmq@.service
  shell: "fleetctl submit rabbitmq@.service && fleetctl start rabbitmq@master.service"
