# starts existing fleet service

# force services parameter to be resolved (not be a unicode object)
- set_fact:
    services: "{{ services }}"

- name: Start fleet services
  shell: "fleetctl start {{ item.name }}"
  with_items: "{{ services }}"
