# stops fleet services in reverse order

# force services parameter to be resolved (not be a unicode object)
- set_fact:
    services: "{{ services }}"

- name: Stop fleet services
  shell: "fleetctl stop {{ item.name }}"
  ignore_errors: True
  with_items: "{{ services[::-1] }}"
